Listen 81

<Directory "/RAID/atomo/home/rhradec/dev/cgru/cgru">
    #Options Indexes FollowSymLinks
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    #Order allow,deny
    Require all granted 
    Allow from all
</Directory>

<VirtualHost *:82>
    DocumentRoot "/RAID/atomo/home/rhradec/dev/cgru/cgru"

    # Set access permission
    <Directory />
        Allow from all
        Require all granted 
    </Directory>

</VirtualHost>
